# Generated by Django 4.2.7 on 2024-02-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_age_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pictures/profilepic.jpg', upload_to='profile_pictures/profile_pictures'),
        ),
    ]
