# Generated by Django 4.2.7 on 2024-02-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_pitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/thumbnails/020/015/926/small_2x/football-pitch-icon-vector.jpg', max_length=500),
        ),
    ]
