# Generated by Django 4.2.7 on 2024-02-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
