# Generated by Django 4.2.7 on 2024-02-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='written_at',
            field=models.DateTimeField(),
        ),
    ]
