# Generated by Django 4.2.7 on 2024-02-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_boughtitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtitem',
            name='item_code',
            field=models.CharField(default='D26BD3', max_length=10, unique=True),
        ),
    ]
