# Generated by Django 4.2.7 on 2024-02-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_alter_boughtitem_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='from_user',
        ),
        migrations.AlterField(
            model_name='boughtitem',
            name='item_code',
            field=models.CharField(default='122363', max_length=10, unique=True),
        ),
    ]
