# Generated by Django 4.2.7 on 2024-02-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_remove_post_from_user_alter_boughtitem_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='from_user',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='boughtitem',
            name='item_code',
            field=models.CharField(default='4444E8', max_length=10, unique=True),
        ),
    ]
