# Generated by Django 4.2.7 on 2024-02-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0017_alter_boughtitem_item_code_friendrequest_friendlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.AlterField(
            model_name='boughtitem',
            name='item_code',
            field=models.CharField(default='D2F8A8', max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
