# Generated by Django 4.2.7 on 2024-02-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_remove_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtitem',
            name='item_code',
            field=models.CharField(default='FAABE3', max_length=10, unique=True),
        ),
    ]
