# Generated by Django 4.2.7 on 2024-02-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0021_alter_boughtitem_bought_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hour',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='boughtitem',
            name='item_code',
            field=models.CharField(default='3A4525', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(default='65D4F6', max_length=10, unique=True),
        ),
    ]
