# Generated by Django 4.2.7 on 2024-02-16 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0024_reservation_participants_alter_boughtitem_item_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtitem',
            name='item_code',
            field=models.CharField(default='C7CEFB', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 17, 18, 56, 511911, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(default='230955', max_length=10, unique=True),
        ),
    ]
